### ISSUE TITLE
Video only plays first 2-3 seconds after downloaded.

### ISSUE THREAD

**Issue by smrdwnnow** [pi-ra/beesy-issue-tracker#43] opened 2024-09-04 13:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I did a test recording, it automaticly downloaded the video file when I went to play the video, only the first few seconds of the video played

### Steps To Reproduce

1. open a google meet
2. record google meet
3. end google meet
4. open downloaded file
5. only plays first few seconds. 

### Environment including version

```Markdown
- Beesy: 0.0.14
- OS:win11
- Browser:chrome
- Media Player:Windows media player
```

**Comment by piyu-sh** [comment] 2024-09-04 17:50
@smrdwnnow 
Please try looking for issues first, this has been addressed earlier as well
Closing it as duplicate of https://github.com/pi-ra/beesy-issue-tracker/issues/40 and https://github.com/pi-ra/beesy-issue-tracker/issues/19.

**Closed by piyu-sh** 2024-09-04 17:50 UTC
Labels: bug
